prow:
  url: https://prow.ci.openshift.org/prowjobs.js
suites:
    # Primary origin suite names
    - openshift-tests
    - openshift-tests-upgrade

    # Sippy synthetic tests
    - sippy

    # ROSA
    - OSD e2e suite

    # Other
    - BackendDisruption
    - Cluster upgrade
    - E2E Suite
    - Kubernetes e2e suite
    - Log Metrics
    - Operator results
    - Symptom Detection
    - Tests Suite
    - cluster install
    - cluster nodes ready
    - cluster nodes

    - gather core dump
    - hypershift-e2e
    - metal infra
    - step graph
releases:
  "4.14":
    jobs:
      periodic-ci-openshift-release-master-nightly-4.14-e2e-aws-sdn-serial: true
      periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade: true
      periodic-ci-openshift-release-master-nightly-4.14-e2e-gcp-sdn: true
