# This file is used as an overlay to customize the generated config, so it contains the Presubmit pseudorelease.
prow:
  url: https://prow.ci.openshift.org/prowjobs.js
releases:
  "4.15":
    hidden: true,
  "4.13":
    gaDate: 2023-05-17
  "4.12":
    gaDate: 2023-01-17
  "4.11":
    gaDate: 2022-08-10
  "4.10":
    gaDate: 2022-03-10
  "4.9":
    gaDate: 2021-10-18
  "4.8":
    gaDate: 2021-07-27
  "4.7":
    gaDate: 2021-02-24
  "4.6":
    gaDate: 2020-10-27
  "3.11":
    jobs:
      periodic-ci-openshift-openshift-ansible-release-3.11-e2e-aws-nightly: true
      periodic-ci-openshift-openshift-ansible-release-3.11-e2e-gcp-nightly: true
      periodic-ci-openshift-origin-release-3.11-e2e-gcp: true
  "Presubmits":
    regexp:
      - "^pull-ci-openshift-.*-(master|main).*-e2e-.*"
      - "^pull-ci-operator-framework.*-(master|main).*-e2e-.*"
