# This file is used as an overlay to customize the generated config, so it contains the Presubmit pseudorelease.
prow:
  url: https://prow.ci.openshift.org/prowjobs.js
releases:
  "3.11":
    jobs:
      periodic-ci-openshift-openshift-ansible-release-3.11-e2e-aws-nightly: true
      periodic-ci-openshift-openshift-ansible-release-3.11-e2e-gcp-nightly: true
      periodic-ci-openshift-origin-release-3.11-e2e-gcp: true
  "4.13":
    regexp:
      - "^periodic-ci-openshift-hypershift.*-4.13-.*"
  "4.12":
    regexp:
      - "^periodic-ci-openshift-hypershift.*-4.12-.*"
  "Presubmits":
    regexp:
      - "^pull-ci-openshift-.*-(master|main).*-e2e-.*"
